const randomWordsArr = [
  "pomme",
  "crayon",
  "voiture",
  "horloge",
  "livre",
  "chaussure",
  "téléphone",
  "table",
  "lunettes",
  "clé",
  "ordinateur",
  "chaise",
  "banane",
  "stylo",
  "vélo",
  "montre",
  "journal",
  "chemise",
  "ballon",
  "tasse",
  "sac à dos",
  "télévision",
  "porte",
  "brosse à dents",
  "guitare",
  "ballon de football",
  "écharpe",
  "bouteille",
  "assiette",
  "canapé",
  "pantalon",
  "cravate",
  "ciseaux",
  "ballon de basketball",
  "ampoule",
  "casserole",
  "marteau",
  "microphone",
  "carte",
  "sandwich",
  "écouteurs",
  "fer à repasser",
  "télécommande",
  "aspirateur",
  "broche",
  "poupée",
  "brosse",
  "carton",
  "clef USB",
  "ruban adhésif",
  "bougie",
  "bouilloire",
  "fraise",
  "boîte",
  "carnet",
  "escabeau",
  "peigne",
  "gant",
  "bouteille d'eau",
  "règle",
  "disque dur",
  "souris d'ordinateur",
  "brosse à cheveux",
  "mouchoir",
  "carte de crédit",
  "couronne",
  "balle",
  "fourchette",
  "couteau",
  "calepin",
  "oreiller",
  "journal",
  "crayon de couleur",
  "parapluie",
  "lunettes de soleil",
  "moule à gâteau",
  "couteau de cuisine",
  "brosse à vaisselle",
  "chargeur de téléphone",
  "ruban",
  "bouée",
  "brosse à chaussures",
  "bouteille de vin",
  "trombone",
  "téléphone portable",
  "cadre photo",
  "haut-parleur",
  "jouet",
  "globe terrestre",
  "masque de sommeil",
  "portefeuille",
  "téléphone fixe",
  "clé à molette",
  "éponge",
  "crayon à sourcils",
  "pinceau",
  "foulard",
  "biberon",
  "pince à épiler",
];

const generateRandomWord = () => {
  let randomWord =
    randomWordsArr[Math.floor(Math.random() * randomWordsArr.length)];
  return randomWord;
};

module.exports = generateRandomWord;
